/* Generated By:JavaCC: Do not edit this line. Parser.java */
        package cn.littleisle.parser;
        import cn.littleisle.ast.*;
        import cn.littleisle.type.*;
        import java.lang.reflect.*;
        import java.util.*;
        import java.io.*;

        public class Parser implements ParserConstants {

                static final public String SOURCE_ENCODING = "UTF-8";
                private String sourceName;

                static public AST parseFile(File file)
                        throws Exception {
                                try{
                                        BufferedReader r=new BufferedReader(
                                                        new InputStreamReader(new FileInputStream(file),SOURCE_ENCODING));
                                        return new Parser(r,"test").parse();
                                }
                                catch(FileNotFoundException ex){
                                        throw new Exception(ex.getMessage());
                                }

                        }
                public Parser(Reader s, String name){
                        this(s);
                        this.sourceName=name;

                }
                public AST parse()throws Exception{
                        try{
                                return compilation_unit();
                        }
                        catch(TokenMgrError err){
                                throw new Exception(err.getMessage());
                        }
                        catch(ParseException ex){
                                throw new Exception(ex.getMessage());
                        }
                }

                static public void main (String[] args){
                        File file=new File(args[0]);
                        try{
                                AST ast=parseFile(file);
                                ast.dump(System.out);
                        }
                        catch(Exception ex){
                                System.out.print(ex.getMessage());
                        }
                }

                protected Location location(Token t){
                        return new Location(sourceName,t);
                }

//the whole pragram
  final public AST compilation_unit() throws ParseException {
    trace_call("compilation_unit");
    try {
        Token t;
        Declarations impdecls,decls;
                t=getToken(1);
      decls = top_defs();
      jj_consume_token(0);
                {if (true) return new AST(location(t),decls);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("compilation_unit");
    }
  }

  final public void import_stmts() throws ParseException {
    trace_call("import_stmts");
    try {
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IMPORT:
          ;
          break;
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        import_stmt();
      }
    } finally {
      trace_return("import_stmts");
    }
  }

  final public void import_stmt() throws ParseException {
    trace_call("import_stmt");
    try {
      jj_consume_token(IMPORT);
      jj_consume_token(IDENTIFIER);
      jj_consume_token(42);
    } finally {
      trace_return("import_stmt");
    }
  }

  final public Declarations top_defs() throws ParseException {
    trace_call("top_defs");
    try {
        Declarations decls= new Declarations();
        StructNode defstruct;
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case STRUCT:
          ;
          break;
        default:
          jj_la1[1] = jj_gen;
          break label_2;
        }
        // LOOKAHEAD(storage() typeref() <IDENTIFIER> "(")
                // defun()
                // | LOOKAHEAD(3)  
                // defvars()
                // | defconst()
                 defstruct = defstruct();
                                decls.addDefstruct(defstruct);
      }
                {if (true) return decls;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("top_defs");
    }
  }

  final public void defvars() throws ParseException {
    trace_call("defvars");
    try {
      storage();
      typeref();
      jj_consume_token(IDENTIFIER);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 43:
        jj_consume_token(43);
        expr();
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 44:
          ;
          break;
        default:
          jj_la1[3] = jj_gen;
          break label_3;
        }
        jj_consume_token(44);
        jj_consume_token(IDENTIFIER);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 43:
          jj_consume_token(43);
          expr();
          break;
        default:
          jj_la1[4] = jj_gen;
          ;
        }
      }
      jj_consume_token(42);
    } finally {
      trace_return("defvars");
    }
  }

  final public void defun() throws ParseException {
    trace_call("defun");
    try {
      storage();
      typeref();
      jj_consume_token(IDENTIFIER);
      jj_consume_token(45);
      params();
      jj_consume_token(46);
      block();
    } finally {
      trace_return("defun");
    }
  }

  final public void defconst() throws ParseException {
    trace_call("defconst");
    try {
      jj_consume_token(CONST);
      typeref();
      jj_consume_token(IDENTIFIER);
      jj_consume_token(43);
      expr();
      jj_consume_token(42);
    } finally {
      trace_return("defconst");
    }
  }

  final public StructNode defstruct() throws ParseException {
    trace_call("defstruct");
    try {
        Token t;
        String n;
        List<Slot> membs;
      t = jj_consume_token(STRUCT);
      n = name();
      membs = member_list();
      jj_consume_token(42);
                {if (true) return new StructNode(location(t),new StructTypeRef(n),n, membs);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("defstruct");
    }
  }

  final public String name() throws ParseException {
    trace_call("name");
    try {
 Token t;
      t = jj_consume_token(IDENTIFIER);
                        {if (true) return t.image;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("name");
    }
  }

  final public void defunion() throws ParseException {
    trace_call("defunion");
    try {
      jj_consume_token(UNION);
      jj_consume_token(IDENTIFIER);
      member_list();
      jj_consume_token(42);
    } finally {
      trace_return("defunion");
    }
  }

  final public void typedef() throws ParseException {
    trace_call("typedef");
    try {
      jj_consume_token(TYPEDEF);
      typeref();
      jj_consume_token(IDENTIFIER);
      jj_consume_token(42);
    } finally {
      trace_return("typedef");
    }
  }

  final public List<Slot> member_list() throws ParseException {
    trace_call("member_list");
    try {
        List<Slot> membs = new ArrayList<Slot>();
        Slot s;
      jj_consume_token(47);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VOID:
        case CHAR:
        case INT:
        case SHORT:
        case LONG:
        case STRUCT:
        case UNION:
        case UNSIGNED:
          ;
          break;
        default:
          jj_la1[5] = jj_gen;
          break label_4;
        }
        s = slot();
        jj_consume_token(42);
                          membs.add(s);
      }
      jj_consume_token(48);
                {if (true) return membs;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("member_list");
    }
  }

  final public Slot slot() throws ParseException {
    trace_call("slot");
    try {
        TypeNode t;
        String n;
      t = type();
      n = name();
                          {if (true) return new Slot(t,n);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("slot");
    }
  }

  final public TypeNode type() throws ParseException {
    trace_call("type");
    try {
        TypeRef ref;
      ref = typeref();
                      {if (true) return new TypeNode(ref);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("type");
    }
  }

  final public void storage() throws ParseException {
    trace_call("storage");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STATIC:
        jj_consume_token(STATIC);
        break;
      default:
        jj_la1[6] = jj_gen;
        ;
      }
    } finally {
      trace_return("storage");
    }
  }

  final public void params() throws ParseException {
    trace_call("params");
    try {
      if (jj_2_1(2147483647)) {
        jj_consume_token(VOID);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VOID:
        case CHAR:
        case INT:
        case SHORT:
        case LONG:
        case STRUCT:
        case UNION:
        case UNSIGNED:
          fixedparams();
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 44:
            jj_consume_token(44);
            jj_consume_token(49);
            break;
          default:
            jj_la1[7] = jj_gen;
            ;
          }
          break;
        default:
          jj_la1[8] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("params");
    }
  }

  final public void fixedparams() throws ParseException {
    trace_call("fixedparams");
    try {
      param();
      label_5:
      while (true) {
        if (jj_2_2(2)) {
          ;
        } else {
          break label_5;
        }
        jj_consume_token(44);
        param();
      }
    } finally {
      trace_return("fixedparams");
    }
  }

  final public void param() throws ParseException {
    trace_call("param");
    try {
      typeref();
      jj_consume_token(IDENTIFIER);
    } finally {
      trace_return("param");
    }
  }

  final public TypeRef typeref() throws ParseException {
    trace_call("typeref");
    try {
        TypeRef ref;
        Token t;
        ParamTypeRefs params;
      ref = typeref_base();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 50:
        case 52:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_6;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 50:
          jj_consume_token(50);
          jj_consume_token(INTEGER);
          jj_consume_token(51);
          break;
        case 52:
          jj_consume_token(52);
          break;
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
                        {if (true) return ref;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("typeref");
    }
  }

  final public TypeRef typeref_base() throws ParseException {
    trace_call("typeref_base");
    try {
        Token t, name;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VOID:
        t = jj_consume_token(VOID);
                           {if (true) return new VoidTypeRef(location(t));}
        break;
      case CHAR:
        jj_consume_token(CHAR);
        break;
      case INT:
        jj_consume_token(INT);
        break;
      case SHORT:
        jj_consume_token(SHORT);
        break;
      case LONG:
        jj_consume_token(LONG);
        break;
      default:
        jj_la1[11] = jj_gen;
        if (jj_2_3(2)) {
          jj_consume_token(UNSIGNED);
          jj_consume_token(CHAR);
        } else if (jj_2_4(2)) {
          jj_consume_token(UNSIGNED);
          jj_consume_token(INT);
        } else if (jj_2_5(2)) {
          jj_consume_token(UNSIGNED);
          jj_consume_token(SHORT);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case UNSIGNED:
            jj_consume_token(UNSIGNED);
            jj_consume_token(LONG);
            break;
          case STRUCT:
            jj_consume_token(STRUCT);
            jj_consume_token(IDENTIFIER);
            break;
          case UNION:
            jj_consume_token(UNION);
            jj_consume_token(IDENTIFIER);
            break;
          default:
            jj_la1[12] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("typeref_base");
    }
  }

  final public void block() throws ParseException {
    trace_call("block");
    try {
      jj_consume_token(47);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case VOID:
        case CHAR:
        case INT:
        case SHORT:
        case LONG:
        case STATIC:
        case STRUCT:
        case UNION:
        case UNSIGNED:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_7;
        }
        defvars();
      }
      stmts();
      jj_consume_token(48);
    } finally {
      trace_return("block");
    }
  }

  final public void stmts() throws ParseException {
    trace_call("stmts");
    try {
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CHARACTER:
        case STRING:
        case IF:
        case WHILE:
        case FOR:
        case BREAK:
        case RETURN:
        case SWITCH:
        case CONTINUE:
        case GOTO:
        case DO:
        case SIZEOF:
        case IDENTIFIER:
        case INTEGER:
        case 42:
        case 45:
        case 47:
        case 52:
        case 75:
        case 78:
        case 79:
        case 82:
        case 83:
        case 84:
        case 85:
          ;
          break;
        default:
          jj_la1[14] = jj_gen;
          break label_8;
        }
        stmt();
      }
    } finally {
      trace_return("stmts");
    }
  }

  final public void stmt() throws ParseException {
    trace_call("stmt");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 42:
        jj_consume_token(42);
        break;
      default:
        jj_la1[15] = jj_gen;
        if (jj_2_6(2)) {
          labeled_stmt();
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case CHARACTER:
          case STRING:
          case SIZEOF:
          case IDENTIFIER:
          case INTEGER:
          case 45:
          case 52:
          case 75:
          case 78:
          case 79:
          case 82:
          case 83:
          case 84:
          case 85:
            expr();
            break;
          case 47:
            block();
            break;
          case IF:
            if_stmt();
            break;
          case WHILE:
            while_stmt();
            break;
          case DO:
            dowhile_stmt();
            break;
          case FOR:
            for_stmt();
            break;
          case SWITCH:
            switch_stmt();
            break;
          case BREAK:
            break_stmt();
            break;
          case CONTINUE:
            continue_stmt();
            break;
          case GOTO:
            goto_stmt();
            break;
          case RETURN:
            return_stmt();
            break;
          default:
            jj_la1[16] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    } finally {
      trace_return("stmt");
    }
  }

  final public void labeled_stmt() throws ParseException {
    trace_call("labeled_stmt");
    try {
      jj_consume_token(IDENTIFIER);
      jj_consume_token(53);
      stmt();
    } finally {
      trace_return("labeled_stmt");
    }
  }

  final public void if_stmt() throws ParseException {
    trace_call("if_stmt");
    try {
      jj_consume_token(IF);
      jj_consume_token(45);
      expr();
      jj_consume_token(46);
      stmt();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ELSE:
        jj_consume_token(ELSE);
        stmt();
        break;
      default:
        jj_la1[17] = jj_gen;
        ;
      }
    } finally {
      trace_return("if_stmt");
    }
  }

  final public void while_stmt() throws ParseException {
    trace_call("while_stmt");
    try {
      jj_consume_token(WHILE);
      jj_consume_token(45);
      expr();
      jj_consume_token(46);
      stmt();
    } finally {
      trace_return("while_stmt");
    }
  }

  final public void dowhile_stmt() throws ParseException {
    trace_call("dowhile_stmt");
    try {
      jj_consume_token(DO);
      stmt();
      jj_consume_token(WHILE);
      jj_consume_token(45);
      expr();
      jj_consume_token(46);
      jj_consume_token(42);
    } finally {
      trace_return("dowhile_stmt");
    }
  }

  final public void for_stmt() throws ParseException {
    trace_call("for_stmt");
    try {
      jj_consume_token(FOR);
      jj_consume_token(45);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CHARACTER:
      case STRING:
      case SIZEOF:
      case IDENTIFIER:
      case INTEGER:
      case 45:
      case 52:
      case 75:
      case 78:
      case 79:
      case 82:
      case 83:
      case 84:
      case 85:
        expr();
        break;
      default:
        jj_la1[18] = jj_gen;
        ;
      }
      jj_consume_token(42);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CHARACTER:
      case STRING:
      case SIZEOF:
      case IDENTIFIER:
      case INTEGER:
      case 45:
      case 52:
      case 75:
      case 78:
      case 79:
      case 82:
      case 83:
      case 84:
      case 85:
        expr();
        break;
      default:
        jj_la1[19] = jj_gen;
        ;
      }
      jj_consume_token(42);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CHARACTER:
      case STRING:
      case SIZEOF:
      case IDENTIFIER:
      case INTEGER:
      case 45:
      case 52:
      case 75:
      case 78:
      case 79:
      case 82:
      case 83:
      case 84:
      case 85:
        expr();
        break;
      default:
        jj_la1[20] = jj_gen;
        ;
      }
      jj_consume_token(46);
      stmt();
    } finally {
      trace_return("for_stmt");
    }
  }

  final public void switch_stmt() throws ParseException {
    trace_call("switch_stmt");
    try {
      jj_consume_token(SWITCH);
      jj_consume_token(45);
      expr();
      jj_consume_token(46);
      jj_consume_token(47);
      case_clauses();
      jj_consume_token(48);
    } finally {
      trace_return("switch_stmt");
    }
  }

  final public void case_clauses() throws ParseException {
    trace_call("case_clauses");
    try {
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CASE:
          ;
          break;
        default:
          jj_la1[21] = jj_gen;
          break label_9;
        }
        case_clause();
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case DEFAULT_:
        default_clause();
        break;
      default:
        jj_la1[22] = jj_gen;
        ;
      }
    } finally {
      trace_return("case_clauses");
    }
  }

  final public void case_clause() throws ParseException {
    trace_call("case_clause");
    try {
      cases();
      case_body();
    } finally {
      trace_return("case_clause");
    }
  }

  final public void cases() throws ParseException {
    trace_call("cases");
    try {
      label_10:
      while (true) {
        jj_consume_token(CASE);
        jj_consume_token(53);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CASE:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_10;
        }
      }
    } finally {
      trace_return("cases");
    }
  }

  final public void default_clause() throws ParseException {
    trace_call("default_clause");
    try {
      jj_consume_token(DEFAULT_);
      jj_consume_token(53);
      case_body();
    } finally {
      trace_return("default_clause");
    }
  }

  final public void case_body() throws ParseException {
    trace_call("case_body");
    try {
      label_11:
      while (true) {
        stmt();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CHARACTER:
        case STRING:
        case IF:
        case WHILE:
        case FOR:
        case BREAK:
        case RETURN:
        case SWITCH:
        case CONTINUE:
        case GOTO:
        case DO:
        case SIZEOF:
        case IDENTIFIER:
        case INTEGER:
        case 42:
        case 45:
        case 47:
        case 52:
        case 75:
        case 78:
        case 79:
        case 82:
        case 83:
        case 84:
        case 85:
          ;
          break;
        default:
          jj_la1[24] = jj_gen;
          break label_11;
        }
      }
    } finally {
      trace_return("case_body");
    }
  }

  final public void break_stmt() throws ParseException {
    trace_call("break_stmt");
    try {
      jj_consume_token(BREAK);
      jj_consume_token(42);
    } finally {
      trace_return("break_stmt");
    }
  }

  final public void continue_stmt() throws ParseException {
    trace_call("continue_stmt");
    try {
      jj_consume_token(CONTINUE);
      jj_consume_token(42);
    } finally {
      trace_return("continue_stmt");
    }
  }

  final public void goto_stmt() throws ParseException {
    trace_call("goto_stmt");
    try {
      jj_consume_token(GOTO);
      jj_consume_token(IDENTIFIER);
      jj_consume_token(42);
    } finally {
      trace_return("goto_stmt");
    }
  }

  final public void return_stmt() throws ParseException {
    trace_call("return_stmt");
    try {
      if (jj_2_7(2)) {
        jj_consume_token(RETURN);
        jj_consume_token(42);
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RETURN:
          jj_consume_token(RETURN);
          expr();
          jj_consume_token(42);
          break;
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("return_stmt");
    }
  }

  final public void expr() throws ParseException {
    trace_call("expr");
    try {
      if (jj_2_8(2147483647)) {
        term();
        jj_consume_token(43);
        expr();
      } else if (jj_2_9(2147483647)) {
        term();
        opssign_op();
        expr();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CHARACTER:
        case STRING:
        case SIZEOF:
        case IDENTIFIER:
        case INTEGER:
        case 45:
        case 52:
        case 75:
        case 78:
        case 79:
        case 82:
        case 83:
        case 84:
        case 85:
          expr10();
          break;
        default:
          jj_la1[26] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr");
    }
  }

  final public void opssign_op() throws ParseException {
    trace_call("opssign_op");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 54:
        jj_consume_token(54);
        break;
      case 55:
        jj_consume_token(55);
        break;
      case 56:
        jj_consume_token(56);
        break;
      case 57:
        jj_consume_token(57);
        break;
      case 58:
        jj_consume_token(58);
        break;
      case 59:
        jj_consume_token(59);
        break;
      case 60:
        jj_consume_token(60);
        break;
      case 61:
        jj_consume_token(61);
        break;
      case 62:
        jj_consume_token(62);
        break;
      case 63:
        jj_consume_token(63);
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("opssign_op");
    }
  }

  final public void expr10() throws ParseException {
    trace_call("expr10");
    try {
      expr9();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 64:
        jj_consume_token(64);
        expr();
        jj_consume_token(53);
        expr10();
        break;
      default:
        jj_la1[28] = jj_gen;
        ;
      }
    } finally {
      trace_return("expr10");
    }
  }

  final public void expr9() throws ParseException {
    trace_call("expr9");
    try {
      expr8();
      label_12:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 65:
          ;
          break;
        default:
          jj_la1[29] = jj_gen;
          break label_12;
        }
        jj_consume_token(65);
        expr8();
      }
    } finally {
      trace_return("expr9");
    }
  }

  final public void expr8() throws ParseException {
    trace_call("expr8");
    try {
      expr7();
      label_13:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 66:
          ;
          break;
        default:
          jj_la1[30] = jj_gen;
          break label_13;
        }
        jj_consume_token(66);
        expr7();
      }
    } finally {
      trace_return("expr8");
    }
  }

  final public void expr7() throws ParseException {
    trace_call("expr7");
    try {
      expr6();
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 67:
        case 68:
        case 69:
        case 70:
        case 71:
        case 72:
          ;
          break;
        default:
          jj_la1[31] = jj_gen;
          break label_14;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 67:
          jj_consume_token(67);
          expr6();
          break;
        case 68:
          jj_consume_token(68);
          expr6();
          break;
        case 69:
          jj_consume_token(69);
          expr6();
          break;
        case 70:
          jj_consume_token(70);
          expr6();
          break;
        case 71:
          jj_consume_token(71);
          expr6();
          break;
        case 72:
          jj_consume_token(72);
          expr6();
          break;
        default:
          jj_la1[32] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr7");
    }
  }

  final public void expr6() throws ParseException {
    trace_call("expr6");
    try {
      expr5();
      label_15:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 73:
          ;
          break;
        default:
          jj_la1[33] = jj_gen;
          break label_15;
        }
        jj_consume_token(73);
        expr5();
      }
    } finally {
      trace_return("expr6");
    }
  }

  final public void expr5() throws ParseException {
    trace_call("expr5");
    try {
      expr4();
      label_16:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 74:
          ;
          break;
        default:
          jj_la1[34] = jj_gen;
          break label_16;
        }
        jj_consume_token(74);
        expr4();
      }
    } finally {
      trace_return("expr5");
    }
  }

  final public void expr4() throws ParseException {
    trace_call("expr4");
    try {
      expr3();
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 75:
          ;
          break;
        default:
          jj_la1[35] = jj_gen;
          break label_17;
        }
        jj_consume_token(75);
        expr3();
      }
    } finally {
      trace_return("expr4");
    }
  }

  final public void expr3() throws ParseException {
    trace_call("expr3");
    try {
      expr2();
      label_18:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 76:
        case 77:
          ;
          break;
        default:
          jj_la1[36] = jj_gen;
          break label_18;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 76:
          jj_consume_token(76);
          expr2();
          break;
        case 77:
          jj_consume_token(77);
          expr2();
          break;
        default:
          jj_la1[37] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr3");
    }
  }

  final public void expr2() throws ParseException {
    trace_call("expr2");
    try {
      expr1();
      label_19:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 78:
        case 79:
          ;
          break;
        default:
          jj_la1[38] = jj_gen;
          break label_19;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 78:
          jj_consume_token(78);
          expr1();
          break;
        case 79:
          jj_consume_token(79);
          expr1();
          break;
        default:
          jj_la1[39] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr2");
    }
  }

  final public void expr1() throws ParseException {
    trace_call("expr1");
    try {
      term();
      label_20:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 52:
        case 80:
        case 81:
          ;
          break;
        default:
          jj_la1[40] = jj_gen;
          break label_20;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 52:
          jj_consume_token(52);
          term();
          break;
        case 80:
          jj_consume_token(80);
          term();
          break;
        case 81:
          jj_consume_token(81);
          term();
          break;
        default:
          jj_la1[41] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("expr1");
    }
  }

  final public void term() throws ParseException {
    trace_call("term");
    try {
      if (jj_2_10(2147483647)) {
        jj_consume_token(45);
        typeref();
        jj_consume_token(46);
        term();
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case CHARACTER:
        case STRING:
        case SIZEOF:
        case IDENTIFIER:
        case INTEGER:
        case 45:
        case 52:
        case 75:
        case 78:
        case 79:
        case 82:
        case 83:
        case 84:
        case 85:
          unary();
          break;
        default:
          jj_la1[42] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("term");
    }
  }

  final public void unary() throws ParseException {
    trace_call("unary");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 82:
        jj_consume_token(82);
        unary();
        break;
      case 83:
        jj_consume_token(83);
        unary();
        break;
      case 78:
        jj_consume_token(78);
        term();
        break;
      case 79:
        jj_consume_token(79);
        term();
        break;
      case 84:
        jj_consume_token(84);
        term();
        break;
      case 85:
        jj_consume_token(85);
        term();
        break;
      case 52:
        jj_consume_token(52);
        term();
        break;
      case 75:
        jj_consume_token(75);
        term();
        break;
      default:
        jj_la1[43] = jj_gen;
        if (jj_2_11(3)) {
          jj_consume_token(SIZEOF);
          jj_consume_token(45);
          typeref();
          jj_consume_token(46);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case SIZEOF:
            jj_consume_token(SIZEOF);
            unary();
            break;
          case CHARACTER:
          case STRING:
          case IDENTIFIER:
          case INTEGER:
          case 45:
            postfix();
            break;
          default:
            jj_la1[44] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    } finally {
      trace_return("unary");
    }
  }

  final public void postfix() throws ParseException {
    trace_call("postfix");
    try {
      primary();
      label_21:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 45:
        case 50:
        case 82:
        case 83:
        case 86:
        case 87:
          ;
          break;
        default:
          jj_la1[45] = jj_gen;
          break label_21;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 82:
          jj_consume_token(82);
          break;
        case 83:
          jj_consume_token(83);
          break;
        case 50:
          jj_consume_token(50);
          expr();
          jj_consume_token(51);
          break;
        case 86:
          jj_consume_token(86);
          jj_consume_token(IDENTIFIER);
          break;
        case 87:
          jj_consume_token(87);
          jj_consume_token(IDENTIFIER);
          break;
        case 45:
          jj_consume_token(45);
          args();
          jj_consume_token(46);
          break;
        default:
          jj_la1[46] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("postfix");
    }
  }

  final public void args() throws ParseException {
    trace_call("args");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CHARACTER:
      case STRING:
      case SIZEOF:
      case IDENTIFIER:
      case INTEGER:
      case 45:
      case 52:
      case 75:
      case 78:
      case 79:
      case 82:
      case 83:
      case 84:
      case 85:
        expr();
        label_22:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case 44:
            ;
            break;
          default:
            jj_la1[47] = jj_gen;
            break label_22;
          }
          jj_consume_token(44);
          expr();
        }
        break;
      default:
        jj_la1[48] = jj_gen;
        ;
      }
    } finally {
      trace_return("args");
    }
  }

  final public void primary() throws ParseException {
    trace_call("primary");
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER:
        jj_consume_token(INTEGER);
        break;
      case CHARACTER:
        jj_consume_token(CHARACTER);
        break;
      case STRING:
        jj_consume_token(STRING);
        break;
      case IDENTIFIER:
        jj_consume_token(IDENTIFIER);
        break;
      case 45:
        jj_consume_token(45);
        expr();
        jj_consume_token(46);
        break;
      default:
        jj_la1[49] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("primary");
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_3R_95() {
    if (jj_scan_token(81)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_94() {
    if (jj_scan_token(80)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_29() {
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_scan_token(45)) return true;
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_38() {
    if (jj_scan_token(82)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_38()) {
    jj_scanpos = xsp;
    if (jj_3R_39()) {
    jj_scanpos = xsp;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) {
    jj_scanpos = xsp;
    if (jj_3R_43()) {
    jj_scanpos = xsp;
    if (jj_3R_44()) {
    jj_scanpos = xsp;
    if (jj_3R_45()) {
    jj_scanpos = xsp;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3R_46()) {
    jj_scanpos = xsp;
    if (jj_3R_47()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_92() {
    if (jj_scan_token(79)) return true;
    if (jj_3R_86()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_3R_24()) return true;
    return false;
  }

  private boolean jj_3R_93() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_90() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_93()) {
    jj_scanpos = xsp;
    if (jj_3R_94()) {
    jj_scanpos = xsp;
    if (jj_3R_95()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_25() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    return false;
  }

  private boolean jj_3R_28() {
    if (jj_scan_token(45)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(46)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_89() {
    if (jj_scan_token(77)) return true;
    if (jj_3R_84()) return true;
    return false;
  }

  private boolean jj_3R_91() {
    if (jj_scan_token(78)) return true;
    if (jj_3R_86()) return true;
    return false;
  }

  private boolean jj_3R_87() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_91()) {
    jj_scanpos = xsp;
    if (jj_3R_92()) return true;
    }
    return false;
  }

  private boolean jj_3R_86() {
    if (jj_3R_25()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_90()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_36() {
    if (jj_scan_token(UNION)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_88() {
    if (jj_scan_token(76)) return true;
    if (jj_3R_84()) return true;
    return false;
  }

  private boolean jj_3R_85() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_88()) {
    jj_scanpos = xsp;
    if (jj_3R_89()) return true;
    }
    return false;
  }

  private boolean jj_3R_35() {
    if (jj_scan_token(STRUCT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_34() {
    if (jj_scan_token(UNSIGNED)) return true;
    if (jj_scan_token(LONG)) return true;
    return false;
  }

  private boolean jj_3R_84() {
    if (jj_3R_86()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_87()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_5() {
    if (jj_scan_token(UNSIGNED)) return true;
    if (jj_scan_token(SHORT)) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_scan_token(UNSIGNED)) return true;
    if (jj_scan_token(INT)) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_scan_token(UNSIGNED)) return true;
    if (jj_scan_token(CHAR)) return true;
    return false;
  }

  private boolean jj_3R_83() {
    if (jj_scan_token(75)) return true;
    if (jj_3R_82()) return true;
    return false;
  }

  private boolean jj_3R_33() {
    if (jj_scan_token(VOID)) return true;
    return false;
  }

  private boolean jj_3R_30() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_33()) {
    jj_scanpos = xsp;
    if (jj_scan_token(16)) {
    jj_scanpos = xsp;
    if (jj_scan_token(17)) {
    jj_scanpos = xsp;
    if (jj_scan_token(18)) {
    jj_scanpos = xsp;
    if (jj_scan_token(19)) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_34()) {
    jj_scanpos = xsp;
    if (jj_3R_35()) {
    jj_scanpos = xsp;
    if (jj_3R_36()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_82() {
    if (jj_3R_84()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_85()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_81() {
    if (jj_scan_token(74)) return true;
    if (jj_3R_80()) return true;
    return false;
  }

  private boolean jj_3R_79() {
    if (jj_scan_token(72)) return true;
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_78() {
    if (jj_scan_token(71)) return true;
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_80() {
    if (jj_3R_82()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_83()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_77() {
    if (jj_scan_token(70)) return true;
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_73() {
    if (jj_scan_token(73)) return true;
    if (jj_3R_72()) return true;
    return false;
  }

  private boolean jj_3R_76() {
    if (jj_scan_token(69)) return true;
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_75() {
    if (jj_scan_token(68)) return true;
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_72() {
    if (jj_3R_80()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_81()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_37() {
    if (jj_scan_token(50)) return true;
    if (jj_scan_token(INTEGER)) return true;
    if (jj_scan_token(51)) return true;
    return false;
  }

  private boolean jj_3R_31() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) return true;
    }
    return false;
  }

  private boolean jj_3R_70() {
    if (jj_3R_72()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_73()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_71() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) {
    jj_scanpos = xsp;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) {
    jj_scanpos = xsp;
    if (jj_3R_78()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_74() {
    if (jj_scan_token(67)) return true;
    if (jj_3R_70()) return true;
    return false;
  }

  private boolean jj_3R_27() {
    if (jj_3R_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_69() {
    if (jj_scan_token(66)) return true;
    if (jj_3R_68()) return true;
    return false;
  }

  private boolean jj_3R_68() {
    if (jj_3R_70()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_71()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_67() {
    if (jj_scan_token(65)) return true;
    if (jj_3R_66()) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(44)) return true;
    if (jj_3R_23()) return true;
    return false;
  }

  private boolean jj_3R_23() {
    if (jj_3R_27()) return true;
    return false;
  }

  private boolean jj_3R_66() {
    if (jj_3R_68()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_69()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_65() {
    if (jj_scan_token(64)) return true;
    if (jj_3R_56()) return true;
    if (jj_scan_token(53)) return true;
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_64() {
    if (jj_3R_66()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_67()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(46)) return true;
    return false;
  }

  private boolean jj_3R_62() {
    if (jj_3R_64()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_25()) return true;
    if (jj_3R_26()) return true;
    return false;
  }

  private boolean jj_3R_60() {
    if (jj_3R_62()) return true;
    return false;
  }

  private boolean jj_3R_59() {
    if (jj_3R_25()) return true;
    if (jj_3R_26()) return true;
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_25()) return true;
    if (jj_scan_token(43)) return true;
    return false;
  }

  private boolean jj_3R_26() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_scan_token(55)) {
    jj_scanpos = xsp;
    if (jj_scan_token(56)) {
    jj_scanpos = xsp;
    if (jj_scan_token(57)) {
    jj_scanpos = xsp;
    if (jj_scan_token(58)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) {
    jj_scanpos = xsp;
    if (jj_scan_token(60)) {
    jj_scanpos = xsp;
    if (jj_scan_token(61)) {
    jj_scanpos = xsp;
    if (jj_scan_token(62)) {
    jj_scanpos = xsp;
    if (jj_scan_token(63)) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_56() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_58() {
    if (jj_3R_25()) return true;
    if (jj_scan_token(43)) return true;
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_scan_token(RETURN)) return true;
    if (jj_scan_token(42)) return true;
    return false;
  }

  private boolean jj_3R_51() {
    if (jj_scan_token(45)) return true;
    if (jj_3R_56()) return true;
    if (jj_scan_token(46)) return true;
    return false;
  }

  private boolean jj_3R_49() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(41)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) {
    jj_scanpos = xsp;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_scan_token(40)) {
    jj_scanpos = xsp;
    if (jj_3R_51()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_55() {
    if (jj_scan_token(45)) return true;
    if (jj_3R_57()) return true;
    if (jj_scan_token(46)) return true;
    return false;
  }

  private boolean jj_3R_54() {
    if (jj_scan_token(87)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_53() {
    if (jj_scan_token(86)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_63() {
    if (jj_scan_token(44)) return true;
    if (jj_3R_56()) return true;
    return false;
  }

  private boolean jj_3R_52() {
    if (jj_scan_token(50)) return true;
    if (jj_3R_56()) return true;
    if (jj_scan_token(51)) return true;
    return false;
  }

  private boolean jj_3R_61() {
    if (jj_3R_56()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_63()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_57() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_61()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_50() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(82)) {
    jj_scanpos = xsp;
    if (jj_scan_token(83)) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_47() {
    if (jj_3R_48()) return true;
    return false;
  }

  private boolean jj_3R_46() {
    if (jj_scan_token(SIZEOF)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(SIZEOF)) return true;
    if (jj_scan_token(45)) return true;
    if (jj_3R_27()) return true;
    if (jj_scan_token(46)) return true;
    return false;
  }

  private boolean jj_3R_45() {
    if (jj_scan_token(75)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_44() {
    if (jj_scan_token(52)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_48() {
    if (jj_3R_49()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_50()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_43() {
    if (jj_scan_token(85)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_42() {
    if (jj_scan_token(84)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_41() {
    if (jj_scan_token(79)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_24() {
    if (jj_scan_token(IDENTIFIER)) return true;
    if (jj_scan_token(53)) return true;
    return false;
  }

  private boolean jj_3R_40() {
    if (jj_scan_token(78)) return true;
    if (jj_3R_25()) return true;
    return false;
  }

  private boolean jj_3R_39() {
    if (jj_scan_token(83)) return true;
    if (jj_3R_32()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[50];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x100000,0x400000,0x0,0x0,0x0,0xcf8000,0x200000,0x0,0xcf8000,0x0,0x0,0xf8000,0xc00000,0xef8000,0xfa004200,0x0,0xfa004200,0x4000000,0x4200,0x4200,0x4200,0x0,0x0,0x0,0xfa004200,0x40000000,0x4200,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x4200,0x0,0x4200,0x0,0x0,0x0,0x4200,0x4200,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x800,0x1000,0x800,0x20,0x0,0x1000,0x20,0x140000,0x140000,0x0,0x20,0x20,0x10a75c,0x400,0x10a35c,0x0,0x102340,0x102340,0x102340,0x1,0x2,0x1,0x10a75c,0x0,0x102340,0xffc00000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x100000,0x100000,0x102340,0x100000,0x2340,0x42000,0x42000,0x1000,0x102340,0x2300,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3cc800,0x0,0x3cc800,0x0,0x3cc800,0x3cc800,0x3cc800,0x0,0x0,0x0,0x3cc800,0x0,0x3cc800,0x0,0x1,0x2,0x4,0x1f8,0x1f8,0x200,0x400,0x800,0x3000,0x3000,0xc000,0xc000,0x30000,0x30000,0x3cc800,0x3cc800,0x0,0xcc0000,0xcc0000,0x0,0x3cc800,0x0,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[11];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 50; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 50; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 50; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 50; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 50; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 50; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        exists = true;
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[88];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 50; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 88; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  private int trace_indent = 0;
  private boolean trace_enabled = true;

/** Enable tracing. */
  final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
    trace_enabled = false;
  }

  private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 11; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

        }
