/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package cn.littleisle.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACES = 1;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 4;
  /** RegularExpression Id. */
  int CHARACTER = 9;
  /** RegularExpression Id. */
  int STRING = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int CHAR = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int SHORT = 18;
  /** RegularExpression Id. */
  int LONG = 19;
  /** RegularExpression Id. */
  int IMPORT = 20;
  /** RegularExpression Id. */
  int STATIC = 21;
  /** RegularExpression Id. */
  int STRUCT = 22;
  /** RegularExpression Id. */
  int UNION = 23;
  /** RegularExpression Id. */
  int CONST = 24;
  /** RegularExpression Id. */
  int IF = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int BREAK = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int SWITCH = 31;
  /** RegularExpression Id. */
  int CASE = 32;
  /** RegularExpression Id. */
  int DEFAULT_ = 33;
  /** RegularExpression Id. */
  int CONTINUE = 34;
  /** RegularExpression Id. */
  int GOTO = 35;
  /** RegularExpression Id. */
  int DO = 36;
  /** RegularExpression Id. */
  int UNSIGNED = 37;
  /** RegularExpression Id. */
  int SIZEOF = 38;
  /** RegularExpression Id. */
  int TYPEDEF = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;
  /** RegularExpression Id. */
  int INTEGER = 41;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_BLOCK_COMMENT = 1;
  /** Lexical state. */
  int IN_CHARACTER = 2;
  /** Lexical state. */
  int CHARACTER_TERM = 3;
  /** Lexical state. */
  int IN_STRING = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACES>",
    "\"/*\"",
    "<token of kind 3>",
    "\"*/\"",
    "\"\\\'\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<token of kind 11>",
    "<token of kind 12>",
    "<token of kind 13>",
    "\"\\\"\"",
    "\"void\"",
    "\"char\"",
    "\"int\"",
    "\"short\"",
    "\"long\"",
    "\"import\"",
    "\"static\"",
    "\"struct\"",
    "\"union\"",
    "\"const\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"for\"",
    "\"break\"",
    "\"return\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"continue\"",
    "\"goto\"",
    "\"do\"",
    "\"unsigned\"",
    "\"sizeof\"",
    "\"typedef\"",
    "<IDENTIFIER>",
    "<INTEGER>",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"...\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\":\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"?\"",
    "\"||\"",
    "\"&&\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\">>\"",
    "\"<<\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"!\"",
    "\"~\"",
    "\".\"",
    "\"->\"",
  };

}
